### ISSUE TITLE
Render all provided images by default

### ISSUE THREAD

**Issue by josephj** [josephj/react-justified-grid#22]
Currently we have the `rows` prop which often excludes extra images from showing. 
This is probably not ideal in most cases. 

While the `rows` prop is undefined, all the images will be rendered.

**Comment by dzienisz** [comment]
I had also this problem

**Comment by josephj** [comment]
@dzienisz 

You can upgrade the package. It's now by default rendering all rows. You probably want to set `showIncompleteRow={true}` to make sure all images are visible.
